def throw_ex(message):
  raise Exception(message)
