def function_that_throws_ex(message):
  raise Exception(message)
